# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.srcs/sources_1/bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
# IP: The module: 'system_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1579 || ORIG_REF_NAME==bd_1579} -quiet] -quiet

# IP: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] -quiet

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0_ooc.xdc

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579_ooc.xdc

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/system_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.srcs/sources_1/bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
# IP: The module: 'system_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1579 || ORIG_REF_NAME==bd_1579} -quiet] -quiet

# IP: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] -quiet

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0_ooc.xdc

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579_ooc.xdc

# XDC: d:/Mukesh/Cam_RoPuf_Hw/project_1/project_1.gen/sources_1/bd/system/ip/system_system_ila_0_1/system_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
